project_id = "jjemlhtyhnncqzpnskor"

[functions.tickets-api]
verify_jwt = false

[functions.email-ingest]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-smartsigma-webhook]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.validate-reset-token]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

[functions.create-ticket-cliente]
verify_jwt = false

[functions.list-tickets-cliente]
verify_jwt = false

[functions.get-ticket-cliente]
verify_jwt = false

[functions.add-ticket-comment-cliente]
verify_jwt = false

[functions.list-tickets]
verify_jwt = false

[functions.save-ticket]
verify_jwt = false

[functions.update-ticket]
verify_jwt = false
