project_id = "jjemlhtyhnncqzpnskor"

[functions.login]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.update-profile]
verify_jwt = false
