import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, CalendarRange, ChartGantt, ChevronDown, ChevronRight, Copy, Link2, ListChecks, MoreHorizontal, Pencil, Plus, Trash2, UsersRound } from "lucide-react";
import CronogramaCalendario from "./CronogramaCalendario";
import CronogramaGantt from "./CronogramaGantt";
import { Atividade, Bloqueio, EXEC_STATUSES, Execucao, execLabel, periodo, statusEfetivo, progresso, statusDerivado } from "./cronogramaModel";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

const db = supabase as any;
const variantStatus = (v: string): "default" | "secondary" | "outline" | "destructive" => v === "CONCLUIDO" ? "default" : v === "BLOQUEADO" || v === "ATRASADO" ? "destructive" : v === "EM_ANDAMENTO" ? "secondary" : "outline";
const br = (v?: string | null) => v ? new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR") : "Sem data";
type Project = { id: number; nome: string; descricao: string | null; data_inicio: string | null; data_fim: string | null; status: string };
type Stage = { id: number; projeto_id: number; nome: string; descricao: string | null; ordem: number; status: string };
type Part = { id: number; etapa_id: number; unidade_id: number };
type Dep = { id: number; etapa_id: number; depende_de_etapa_id: number };
type Shop = { unidade_id: number; unidades?: { nome_unidade: string } };
const emptyAtv = { nome: "", responsavel: "", observacoes: "", data_inicio: "", data_fim: "", status: "NAO_INICIADO" };

export default function CronogramaConstrutor({ lojas, admin }: { lojas: Shop[]; admin: boolean }) {
  const { toast } = useToast();
  const [projects, setProjects] = useState<Project[]>([]), [stages, setStages] = useState<Stage[]>([]), [parts, setParts] = useState<Part[]>([]), [deps, setDeps] = useState<Dep[]>([]);
  const [atvs, setAtvs] = useState<Atividade[]>([]), [exes, setExes] = useState<Execucao[]>([]), [blqs, setBlqs] = useState<Bloqueio[]>([]);
  const [editAtv, setEditAtv] = useState<{ etapa: Stage; atv?: Atividade } | null>(null), [atvForm, setAtvForm] = useState(emptyAtv), [selected, setSelected] = useState<Set<number>>(new Set()), [search, setSearch] = useState("");
  const [projectId, setProjectId] = useState<number | null>(null), [loading, setLoading] = useState(true), [mode, setMode] = useState<"estrutura" | "calendario" | "gantt">("estrutura"), [open, setOpen] = useState<Set<number>>(new Set());
  const [editStage, setEditStage] = useState<Stage | "new" | null>(null), [stageForm, setStageForm] = useState({ nome: "", descricao: "" });
  const [stageDialogKind, setStageDialogKind] = useState<"estrutura" | "etapa">("estrutura");
  const [depStage, setDepStage] = useState<Stage | null>(null), [depTarget, setDepTarget] = useState("");
  const [remove, setRemove] = useState<{ table: string; id: number; label: string } | null>(null), [saving, setSaving] = useState(false);

  const load = async () => {
    const [p, e, u, d, a, x, b] = await Promise.all([db.from("elev_cronograma_projetos").select("*").eq("ativo", true).order("id"), db.from("elev_cronograma_etapas").select("*").order("ordem"), db.from("elev_cronograma_etapa_unidades").select("id, etapa_id, unidade_id"), db.from("elev_cronograma_dependencias").select("*"), db.from("elev_cronograma_atividades").select("*").order("ordem"), db.from("elev_cronograma_execucoes").select("*").limit(5000), db.from("elev_cronograma_bloqueios").select("*").order("data_inicio")]);
    const error = p.error || e.error || u.error || d.error || a.error || x.error || b.error;
    if (error) toast({ title: "Erro ao carregar cronograma", description: error.message, variant: "destructive" });
    const ps = p.data || []; setProjects(ps); setStages(e.data || []); setParts(u.data || []); setDeps(d.data || []); setAtvs(a.data || []); setExes(x.data || []); setBlqs(b.data || []); setProjectId((v) => v && ps.some((x: Project) => x.id === v) ? v : ps[0]?.id ?? null); setLoading(false);
  };
  useEffect(() => { load(); let ch = db.channel("elev-cronograma-rt"); ["elev_cronograma_etapas", "elev_cronograma_etapa_unidades", "elev_cronograma_dependencias", "elev_cronograma_atividades", "elev_cronograma_execucoes", "elev_cronograma_bloqueios"].forEach((t) => { ch = ch.on("postgres_changes", { event: "*", schema: "public", table: t }, load); }); ch.subscribe(); return () => { db.removeChannel(ch); }; }, []);
  const project = projects.find((x) => x.id === projectId), visible = useMemo(() => stages.filter((x) => x.projeto_id === projectId).sort((a, b) => a.ordem - b.ordem || a.id - b.id), [stages, projectId]);
  const shop = (id: number) => lojas.find((x) => x.unidade_id === id)?.unidades?.nome_unidade || `UNIDADE ${id}`;
  const aStage = (id: number) => atvs.filter((a) => a.etapa_id === id).sort((a, b) => (a.data_inicio || "9").localeCompare(b.data_inicio || "9") || a.ordem - b.ordem || a.id - b.id);
  const unitIds = (atvId: number) => [...new Set(exes.filter((e) => e.atividade_id === atvId).map((e) => parts.find((p) => p.id === e.etapa_unidade_id)?.unidade_id).filter(Boolean) as number[])];
  const unidadesDe = (atvId: number) => unitIds(atvId).map(shop).sort();
  const projAtvs = visible.flatMap((s) => aStage(s.id)), totalProgress = progresso(projAtvs), projPeriod = periodo(projAtvs);
  const fail = (title: string, error: any) => toast({ title, description: error?.message, variant: "destructive" });

  const showStage = (s?: Stage, kind: "estrutura" | "etapa" = "estrutura") => { setStageDialogKind(kind); setEditStage(s || "new"); setStageForm({ nome: s?.nome || "", descricao: s?.descricao || "" }); };
  const saveStage = async () => { if (!projectId || !stageForm.nome.trim()) return; setSaving(true); const payload = { nome: stageForm.nome.trim(), descricao: stageForm.descricao || null }; const r = editStage === "new" ? await db.from("elev_cronograma_etapas").insert({ ...payload, projeto_id: projectId, ordem: visible.length + 1, status: "NAO_INICIADO" }) : await db.from("elev_cronograma_etapas").update(payload).eq("id", (editStage as Stage).id); setSaving(false); if (r.error) return fail("Não foi possível salvar", r.error); setEditStage(null); toast({ title: stageDialogKind === "estrutura" ? "Estrutura salva" : "Etapa salva" }); load(); };
  const duplicate = async (s: Stage) => { const { data, error } = await db.from("elev_cronograma_etapas").insert({ projeto_id: s.projeto_id, nome: `${s.nome} — Cópia`, descricao: s.descricao, ordem: visible.length + 1, status: "NAO_INICIADO" }).select("id").single(); if (error || !data) return fail("Não foi possível duplicar", error); for (const a of aStage(s.id)) { const { data: na } = await db.from("elev_cronograma_atividades").insert({ etapa_id: data.id, nome: a.nome, responsavel: a.responsavel, observacoes: a.observacoes, data_inicio: a.data_inicio, data_fim: a.data_fim, ordem: a.ordem, status: "NAO_INICIADO" }).select("id").single(); if (na) await linkUnits(data.id, na.id, unitIds(a.id), []); } toast({ title: "Etapa duplicada" }); load(); };
  const move = async (s: Stage, dir: -1 | 1) => { const i = visible.findIndex((x) => x.id === s.id), other = visible[i + dir]; if (!other) return; await Promise.all([db.from("elev_cronograma_etapas").update({ ordem: other.ordem }).eq("id", s.id), db.from("elev_cronograma_etapas").update({ ordem: s.ordem }).eq("id", other.id)]); load(); };

  /** Associa unidades à atividade, reutilizando a participação da unidade na etapa (usada pelo Kanban). */
  const linkUnits = async (etapaId: number, atvId: number, add: number[], del: number[]) => {
    if (add.length) {
      const { data: ex } = await db.from("elev_cronograma_etapa_unidades").select("id, unidade_id").eq("etapa_id", etapaId).in("unidade_id", add);
      const have = new Map<number, number>((ex || []).map((p: Part) => [p.unidade_id, p.id]));
      const missing = add.filter((u) => !have.has(u));
      if (missing.length) { const { data: novos, error } = await db.from("elev_cronograma_etapa_unidades").insert(missing.map((u) => ({ etapa_id: etapaId, unidade_id: u, status: "NAO_INICIADO" }))).select("id, unidade_id"); if (error) throw error; (novos || []).forEach((p: Part) => have.set(p.unidade_id, p.id)); }
      const { error } = await db.from("elev_cronograma_execucoes").upsert(add.map((u) => ({ atividade_id: atvId, etapa_unidade_id: have.get(u), status: "NAO_INICIADO" })), { onConflict: "atividade_id,etapa_unidade_id", ignoreDuplicates: true }); if (error) throw error;
    }
    if (del.length) { const ids = exes.filter((e) => e.atividade_id === atvId && del.includes(parts.find((p) => p.id === e.etapa_unidade_id)?.unidade_id || -1)).map((e) => e.id); if (ids.length) { const { error } = await db.from("elev_cronograma_execucoes").delete().in("id", ids); if (error) throw error; } }
  };

  const showAtv = (etapa: Stage, atv?: Atividade) => { setEditAtv({ etapa, atv }); setSearch(""); setSelected(new Set(atv ? unitIds(atv.id) : [])); setAtvForm(atv ? { nome: atv.nome, responsavel: atv.responsavel || "", observacoes: atv.observacoes || "", data_inicio: atv.data_inicio || "", data_fim: atv.data_fim || "", status: atv.status } : emptyAtv); };
  const saveAtv = async () => {
    if (!editAtv || !atvForm.nome.trim()) return;
    if (atvForm.data_inicio && atvForm.data_fim && atvForm.data_fim < atvForm.data_inicio) return fail("Datas inválidas", { message: "A data de fim não pode ser antes da data de início." });
    setSaving(true);
    try {
      const payload = { nome: atvForm.nome.trim(), responsavel: atvForm.responsavel || null, observacoes: atvForm.observacoes || null, data_inicio: atvForm.data_inicio || null, data_fim: atvForm.data_fim || atvForm.data_inicio || null, status: atvForm.status, concluido_em: atvForm.status === "CONCLUIDO" ? new Date().toISOString() : null };
      let id = editAtv.atv?.id;
      if (id) { const { error } = await db.from("elev_cronograma_atividades").update(payload).eq("id", id); if (error) throw error; }
      else { const { data, error } = await db.from("elev_cronograma_atividades").insert({ ...payload, etapa_id: editAtv.etapa.id, ordem: aStage(editAtv.etapa.id).length + 1 }).select("id").single(); if (error) throw error; id = data.id; }
      const old = id && editAtv.atv ? unitIds(id) : [];
      await linkUnits(editAtv.etapa.id, id!, [...selected].filter((u) => !old.includes(u)), old.filter((u) => !selected.has(u)));
      setEditAtv(null); toast({ title: "Atividade salva" }); load();
    } catch (e) { fail("Não foi possível salvar", e); } finally { setSaving(false); }
  };
  const updateAtv = async (a: Atividade, patch: Partial<Atividade>) => { const next: any = { ...patch }; if (patch.status) next.concluido_em = patch.status === "CONCLUIDO" ? new Date().toISOString() : null; setAtvs((xs) => xs.map((x) => x.id === a.id ? { ...x, ...next } : x)); const { error } = await db.from("elev_cronograma_atividades").update(next).eq("id", a.id); if (error) { fail("Não foi possível atualizar", error); load(); } };
  const addDep = async () => { if (!depStage || !depTarget) return; const { error } = await db.from("elev_cronograma_dependencias").insert({ etapa_id: depStage.id, depende_de_etapa_id: Number(depTarget), tipo: "OPCIONAL" }); error ? fail("Não foi possível adicionar", error) : (setDepTarget(""), load()); };
  const deleteItem = async () => { if (!remove) return; const { error } = await db.from(remove.table).delete().eq("id", remove.id); error ? fail("Não foi possível excluir", error) : toast({ title: `${remove.label} excluída` }); setRemove(null); load(); };

  if (loading) return <p className="text-sm text-muted-foreground">Carregando cronograma...</p>;
  if (!project) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Nenhum projeto disponível.</CardContent></Card>;
  return <div className="space-y-4">
    <Card><CardHeader className="pb-3"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><CardTitle className="text-lg">{project.nome}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{project.descricao}</p></div><div className="flex flex-wrap gap-2"><Select value={String(project.id)} onValueChange={(v) => setProjectId(Number(v))}><SelectTrigger className="w-[240px]"><SelectValue /></SelectTrigger><SelectContent>{projects.map((p) => <SelectItem key={p.id} value={String(p.id)}>{p.nome}</SelectItem>)}</SelectContent></Select>{admin && <Button onClick={() => showStage()}><Plus className="mr-1 h-4 w-4" />Nova estrutura</Button>}</div></div></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2 text-sm"><Badge variant={variantStatus(statusDerivado(projAtvs))}>{execLabel(statusDerivado(projAtvs))}</Badge><span>{br(projPeriod.inicio || project.data_inicio)} → {br(projPeriod.fim || project.data_fim)}</span><span className="text-muted-foreground">{projAtvs.filter((e) => e.status === "CONCLUIDO").length}/{projAtvs.length} atividades concluídas</span><strong className="ml-auto">{totalProgress}%</strong></div><Progress value={totalProgress} /></CardContent></Card>
    <div className="flex w-fit rounded-md border p-1"><Button size="sm" variant={mode === "estrutura" ? "default" : "ghost"} onClick={() => setMode("estrutura")}><UsersRound className="mr-1 h-4 w-4" />Etapas</Button><Button size="sm" variant={mode === "gantt" ? <CronogramaGantt stages={visible} atividades={projAtvs} unidadesDe={unidadesDe} /> : mode === "calendario" ? "default" : "ghost"} onClick={() => setMode("calendario")}><CalendarRange className="mr-1 h-4 w-4" />Calendário</Button><Button size="sm" variant={mode === "gantt" ? "default" : "ghost"} onClick={() => setMode("gantt")}><ChartGantt className="mr-1 h-4 w-4" />Gantt</Button></div>
    {mode === "gantt" ? <CronogramaGantt stages={visible} atividades={projAtvs} unidadesDe={unidadesDe} /> : mode === "calendario" ? <CronogramaCalendario stages={visible} atividades={atvs} unidadesDe={unidadesDe} bloqueios={blqs.filter((b) => b.projeto_id === projectId)} /> : <div className="space-y-3">{admin && <div className="flex justify-end"><Button onClick={() => showStage(undefined, "etapa")}><Plus className="mr-1 h-4 w-4" />Nova Etapa</Button></div>}{visible.map((s, index) => { const as = aStage(s.id), per = periodo(as), st = statusDerivado(as), pr = progresso(as), expanded = open.has(s.id); return <Card key={s.id}><CardHeader className="p-4"><div className="flex items-start gap-2"><Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => setOpen((o) => { const n = new Set(o); n.has(s.id) ? n.delete(s.id) : n.add(s.id); return n; })}>{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</Button><div className="min-w-0 flex-1 space-y-2"><div className="flex flex-wrap items-center gap-2"><CardTitle className="text-base">{s.ordem}. {s.nome}</CardTitle><Badge variant={variantStatus(st)}>{execLabel(st)}</Badge><Badge variant="outline">{as.length} atividade(s)</Badge></div>{s.descricao && <p className="text-sm text-muted-foreground">{s.descricao}</p>}<p className="text-xs text-muted-foreground">{br(per.inicio)} → {br(per.fim)} · {pr}% concluído ({as.filter((a) => a.status === "CONCLUIDO").length}/{as.length} atividades){deps.some((d) => d.etapa_id === s.id) ? ` · ${deps.filter((d) => d.etapa_id === s.id).length} dependência(s)` : ""}</p><Progress value={pr} className="h-1.5" /></div>{admin && <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => showStage(s)}><Pencil className="mr-2 h-4 w-4" />Editar</DropdownMenuItem><DropdownMenuItem onClick={() => showAtv(s)}><ListChecks className="mr-2 h-4 w-4" />Nova atividade</DropdownMenuItem><DropdownMenuItem onClick={() => setDepStage(s)}><Link2 className="mr-2 h-4 w-4" />Dependências</DropdownMenuItem><DropdownMenuItem disabled={!index} onClick={() => move(s, -1)}><ArrowUp className="mr-2 h-4 w-4" />Mover acima</DropdownMenuItem><DropdownMenuItem disabled={index === visible.length - 1} onClick={() => move(s, 1)}><ArrowDown className="mr-2 h-4 w-4" />Mover abaixo</DropdownMenuItem><DropdownMenuItem onClick={() => duplicate(s)}><Copy className="mr-2 h-4 w-4" />Duplicar</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={() => setRemove({ table: "elev_cronograma_etapas", id: s.id, label: "Etapa" })}><Trash2 className="mr-2 h-4 w-4" />Excluir</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div></CardHeader>
      {expanded && <CardContent className="space-y-3 border-t p-4"><div className="flex justify-between"><strong className="text-sm">Atividades</strong>{admin && <Button size="sm" variant="outline" onClick={() => showAtv(s)}><Plus className="mr-1 h-4 w-4" />Atividade</Button>}</div>{!as.length && <p className="text-sm text-muted-foreground">Nenhuma atividade cadastrada.</p>}
        {as.map((a) => { const us = unidadesDe(a.id), ef = statusEfetivo(a); return <div key={a.id} className="space-y-3 rounded-md border p-3">
          <div className="flex items-center gap-2"><ListChecks className="h-4 w-4 text-primary" /><p className="font-medium">{a.nome}</p>{ef === "ATRASADO" && <Badge variant="destructive">Atraso</Badge>}{admin && <Button size="icon" variant="ghost" className="ml-auto h-7 w-7" onClick={() => showAtv(s, a)}><Pencil className="h-3.5 w-3.5" /></Button>}{admin && <Button size="icon" variant="ghost" className="h-7 w-7 text-destructive" onClick={() => setRemove({ table: "elev_cronograma_atividades", id: a.id, label: "Atividade" })}><Trash2 className="h-3.5 w-3.5" /></Button>}</div>
          <div className="grid grid-cols-1 items-end gap-3 sm:grid-cols-[160px_160px_180px_1fr]"><div className="space-y-1"><Label className="text-xs text-muted-foreground">Data de início</Label><Input type="date" className="h-8" disabled={!admin} value={a.data_inicio || ""} onChange={(ev) => updateAtv(a, { data_inicio: ev.target.value || null, ...(a.data_fim && ev.target.value && a.data_fim < ev.target.value ? { data_fim: ev.target.value } : {}) })} /></div><div className="space-y-1"><Label className="text-xs text-muted-foreground">Data de fim</Label><Input type="date" className="h-8" disabled={!admin} min={a.data_inicio || undefined} value={a.data_fim || ""} onChange={(ev) => updateAtv(a, { data_fim: ev.target.value || null })} /></div><div className="space-y-1"><Label className="text-xs text-muted-foreground">Status</Label><Select value={a.status} onValueChange={(v) => updateAtv(a, { status: v })}><SelectTrigger className="h-8"><SelectValue /></SelectTrigger><SelectContent>{EXEC_STATUSES.map(([k, l]) => <SelectItem key={k} value={k}>{l}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label className="text-xs text-muted-foreground">Responsável</Label><p className="flex h-8 items-center text-sm">{a.responsavel || "—"}</p></div></div>
          {a.observacoes && <p className="text-xs text-muted-foreground">{a.observacoes}</p>}
          <div><p className="mb-1 text-xs text-muted-foreground">Unidades ({us.length})</p><div className="flex flex-wrap gap-1">{us.map((n) => <Badge key={n} variant="secondary">{n}</Badge>)}{!us.length && <span className="text-xs text-muted-foreground">Nenhuma unidade associada.</span>}</div></div>
        </div>; })}
      </CardContent>}</Card>; })}</div>}

    <Dialog open={editStage !== null} onOpenChange={(v) => !v && setEditStage(null)}><DialogContent><DialogHeader><DialogTitle>{editStage === "new" ? (stageDialogKind === "estrutura" ? "Nova Estrutura" : "Nova Etapa") : (stageDialogKind === "estrutura" ? "Editar Estrutura" : "Editar Etapa")}</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>{stageDialogKind === "estrutura" ? "Nome da estrutura *" : "Nome da etapa *"}</Label><Input aria-label={stageDialogKind === "estrutura" ? "Nome da estrutura" : "Nome da etapa"} value={stageForm.nome} onChange={(e) => setStageForm({ ...stageForm, nome: e.target.value })} /></div><div><Label>Descrição</Label><Textarea value={stageForm.descricao} onChange={(e) => setStageForm({ ...stageForm, descricao: e.target.value })} /></div><p className="text-xs text-muted-foreground">{stageDialogKind === "estrutura" ? "O período e o status da estrutura são calculados automaticamente pelas atividades." : "O período e o status da etapa são calculados automaticamente pelas atividades."}</p></div><DialogFooter><Button variant="outline" onClick={() => setEditStage(null)}>Cancelar</Button><Button disabled={saving || !stageForm.nome.trim()} onClick={saveStage}>Salvar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={editAtv !== null} onOpenChange={(v) => !v && setEditAtv(null)}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{editAtv?.atv ? "Editar atividade" : "Nova atividade"}</DialogTitle></DialogHeader><div className="max-h-[70vh] space-y-3 overflow-y-auto pr-1">
      <p className="text-xs text-muted-foreground">Etapa: <strong>{editAtv?.etapa.nome}</strong></p>
      <div><Label>Nome da atividade *</Label><Input value={atvForm.nome} onChange={(e) => setAtvForm({ ...atvForm, nome: e.target.value })} /></div>
      <div className="grid grid-cols-2 gap-3"><div><Label>Data de início</Label><Input type="date" value={atvForm.data_inicio} onChange={(e) => setAtvForm({ ...atvForm, data_inicio: e.target.value })} /></div><div><Label>Data de fim</Label><Input type="date" min={atvForm.data_inicio || undefined} value={atvForm.data_fim} onChange={(e) => setAtvForm({ ...atvForm, data_fim: e.target.value })} /></div></div>
      <div className="grid grid-cols-2 gap-3"><div><Label>Status</Label><Select value={atvForm.status} onValueChange={(v) => setAtvForm({ ...atvForm, status: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{EXEC_STATUSES.map(([k, l]) => <SelectItem key={k} value={k}>{l}</SelectItem>)}</SelectContent></Select></div><div><Label>Responsável</Label><Input value={atvForm.responsavel} onChange={(e) => setAtvForm({ ...atvForm, responsavel: e.target.value })} /></div></div>
      <div><Label>Observações</Label><Textarea value={atvForm.observacoes} onChange={(e) => setAtvForm({ ...atvForm, observacoes: e.target.value })} /></div>
      <div className="space-y-2"><div className="flex items-center justify-between"><Label>Unidades ({selected.size})</Label><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => setSelected(new Set(lojas.map((l) => l.unidade_id)))}>Todas</Button><Button size="sm" variant="ghost" onClick={() => setSelected(new Set())}>Nenhuma</Button></div></div><Input placeholder="Buscar unidade..." value={search} onChange={(e) => setSearch(e.target.value)} /><div className="max-h-56 space-y-1 overflow-y-auto rounded border p-2">{lojas.filter((l) => shop(l.unidade_id).toLowerCase().includes(search.toLowerCase())).sort((a, b) => shop(a.unidade_id).localeCompare(shop(b.unidade_id))).map((l) => <label key={l.unidade_id} className="flex cursor-pointer items-center gap-3 rounded p-1.5 text-sm hover:bg-muted"><Checkbox checked={selected.has(l.unidade_id)} onCheckedChange={(v) => setSelected((old) => { const n = new Set(old); v ? n.add(l.unidade_id) : n.delete(l.unidade_id); return n; })} />{shop(l.unidade_id)}</label>)}</div></div>
    </div><DialogFooter><Button variant="outline" onClick={() => setEditAtv(null)}>Cancelar</Button><Button disabled={saving || !atvForm.nome.trim()} onClick={saveAtv}>Salvar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={depStage !== null} onOpenChange={(v) => !v && setDepStage(null)}><DialogContent><DialogHeader><DialogTitle>Dependências opcionais</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">A ordem não cria dependência. Adicione somente quando necessário.</p><div className="flex gap-2"><Select value={depTarget} onValueChange={setDepTarget}><SelectTrigger><SelectValue placeholder="Selecione uma etapa" /></SelectTrigger><SelectContent>{visible.filter((s) => s.id !== depStage?.id && !deps.some((d) => d.etapa_id === depStage?.id && d.depende_de_etapa_id === s.id)).map((s) => <SelectItem key={s.id} value={String(s.id)}>{s.nome}</SelectItem>)}</SelectContent></Select><Button disabled={!depTarget} onClick={addDep}>Adicionar</Button></div>{deps.filter((d) => d.etapa_id === depStage?.id).map((d) => <div key={d.id} className="flex items-center justify-between rounded border p-2 text-sm"><span>Depende de: {visible.find((s) => s.id === d.depende_de_etapa_id)?.nome}</span><Button size="icon" variant="ghost" className="h-8 w-8 text-destructive" onClick={async () => { await db.from("elev_cronograma_dependencias").delete().eq("id", d.id); load(); }}><Trash2 className="h-4 w-4" /></Button></div>)}<DialogFooter><Button onClick={() => setDepStage(null)}>Concluir</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={remove !== null} onOpenChange={(v) => !v && setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir {remove?.label.toLowerCase()}?</AlertDialogTitle><AlertDialogDescription>Os vínculos internos também serão removidos. As unidades do cadastro não são afetadas.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={deleteItem}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
