
CREATE TABLE public.pessoas (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome character varying NOT NULL,
  telefone character varying,
  unidade_id integer NOT NULL REFERENCES public.unidades(id) ON DELETE CASCADE,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now()
);

CREATE TABLE public.responsaveis (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome character varying NOT NULL,
  telefone character varying,
  email character varying,
  empresa_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now()
);

ALTER TABLE public.pessoas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responsaveis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anon full access" ON public.pessoas FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access" ON public.pessoas FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Anon full access" ON public.responsaveis FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access" ON public.responsaveis FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER atualizar_timestamp_pessoas BEFORE UPDATE ON public.pessoas FOR EACH ROW EXECUTE FUNCTION public.atualizar_timestamp();
CREATE TRIGGER atualizar_timestamp_responsaveis BEFORE UPDATE ON public.responsaveis FOR EACH ROW EXECUTE FUNCTION public.atualizar_timestamp();
