CREATE TABLE public.elev_cronograma_projetos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  descricao text,
  data_inicio date,
  data_fim date,
  status text NOT NULL DEFAULT 'NAO_INICIADO',
  ativo boolean NOT NULL DEFAULT true,
  criado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.elev_cronograma_projetos TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.elev_cronograma_projetos TO authenticated;
GRANT ALL ON public.elev_cronograma_projetos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.elev_cronograma_projetos_id_seq TO authenticated, service_role;
ALTER TABLE public.elev_cronograma_projetos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "elev cron projetos staff read" ON public.elev_cronograma_projetos FOR SELECT TO authenticated USING (public.fn_elev_is_staff());
CREATE POLICY "elev cron projetos admin insert" ON public.elev_cronograma_projetos FOR INSERT TO authenticated WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron projetos admin update" ON public.elev_cronograma_projetos FOR UPDATE TO authenticated USING (public.fn_elev_is_admin()) WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron projetos admin delete" ON public.elev_cronograma_projetos FOR DELETE TO authenticated USING (public.fn_elev_is_admin());

CREATE TABLE public.elev_cronograma_etapas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projeto_id bigint NOT NULL REFERENCES public.elev_cronograma_projetos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  descricao text,
  data_inicio date,
  data_fim date,
  ordem integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'NAO_INICIADO',
  criado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elev_cronograma_etapas TO authenticated;
GRANT ALL ON public.elev_cronograma_etapas TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.elev_cronograma_etapas_id_seq TO authenticated, service_role;
ALTER TABLE public.elev_cronograma_etapas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "elev cron etapas staff read" ON public.elev_cronograma_etapas FOR SELECT TO authenticated USING (public.fn_elev_is_staff());
CREATE POLICY "elev cron etapas admin insert" ON public.elev_cronograma_etapas FOR INSERT TO authenticated WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron etapas admin update" ON public.elev_cronograma_etapas FOR UPDATE TO authenticated USING (public.fn_elev_is_admin()) WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron etapas admin delete" ON public.elev_cronograma_etapas FOR DELETE TO authenticated USING (public.fn_elev_is_admin());

CREATE TABLE public.elev_cronograma_etapa_unidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etapa_id bigint NOT NULL REFERENCES public.elev_cronograma_etapas(id) ON DELETE CASCADE,
  unidade_id integer NOT NULL REFERENCES public.unidades(id) ON DELETE CASCADE,
  data_inicio date,
  data_fim date,
  status text NOT NULL DEFAULT 'NAO_INICIADO',
  progresso_manual numeric(5,2),
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE (etapa_id, unidade_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elev_cronograma_etapa_unidades TO authenticated;
GRANT ALL ON public.elev_cronograma_etapa_unidades TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.elev_cronograma_etapa_unidades_id_seq TO authenticated, service_role;
ALTER TABLE public.elev_cronograma_etapa_unidades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "elev cron unidades staff read" ON public.elev_cronograma_etapa_unidades FOR SELECT TO authenticated USING (public.fn_elev_is_staff());
CREATE POLICY "elev cron unidades admin insert" ON public.elev_cronograma_etapa_unidades FOR INSERT TO authenticated WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron unidades staff update" ON public.elev_cronograma_etapa_unidades FOR UPDATE TO authenticated USING (public.fn_elev_is_staff()) WITH CHECK (public.fn_elev_is_staff());
CREATE POLICY "elev cron unidades admin delete" ON public.elev_cronograma_etapa_unidades FOR DELETE TO authenticated USING (public.fn_elev_is_admin());

CREATE TABLE public.elev_cronograma_faciais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etapa_unidade_id bigint NOT NULL REFERENCES public.elev_cronograma_etapa_unidades(id) ON DELETE CASCADE,
  nome text NOT NULL,
  descricao text,
  status text NOT NULL DEFAULT 'NAO_INICIADO',
  observacoes text,
  pendencias text,
  ordem integer NOT NULL DEFAULT 0,
  concluido_em timestamptz,
  atualizado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elev_cronograma_faciais TO authenticated;
GRANT ALL ON public.elev_cronograma_faciais TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.elev_cronograma_faciais_id_seq TO authenticated, service_role;
ALTER TABLE public.elev_cronograma_faciais ENABLE ROW LEVEL SECURITY;
CREATE POLICY "elev cron faciais staff read" ON public.elev_cronograma_faciais FOR SELECT TO authenticated USING (public.fn_elev_is_staff());
CREATE POLICY "elev cron faciais admin insert" ON public.elev_cronograma_faciais FOR INSERT TO authenticated WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron faciais staff update" ON public.elev_cronograma_faciais FOR UPDATE TO authenticated USING (public.fn_elev_is_staff()) WITH CHECK (public.fn_elev_is_staff());
CREATE POLICY "elev cron faciais admin delete" ON public.elev_cronograma_faciais FOR DELETE TO authenticated USING (public.fn_elev_is_admin());

CREATE TABLE public.elev_cronograma_dependencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etapa_id bigint NOT NULL REFERENCES public.elev_cronograma_etapas(id) ON DELETE CASCADE,
  depende_de_etapa_id bigint NOT NULL REFERENCES public.elev_cronograma_etapas(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'OPCIONAL',
  criado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE (etapa_id, depende_de_etapa_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elev_cronograma_dependencias TO authenticated;
GRANT ALL ON public.elev_cronograma_dependencias TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.elev_cronograma_dependencias_id_seq TO authenticated, service_role;
ALTER TABLE public.elev_cronograma_dependencias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "elev cron deps staff read" ON public.elev_cronograma_dependencias FOR SELECT TO authenticated USING (public.fn_elev_is_staff());
CREATE POLICY "elev cron deps admin insert" ON public.elev_cronograma_dependencias FOR INSERT TO authenticated WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron deps admin update" ON public.elev_cronograma_dependencias FOR UPDATE TO authenticated USING (public.fn_elev_is_admin()) WITH CHECK (public.fn_elev_is_admin());
CREATE POLICY "elev cron deps admin delete" ON public.elev_cronograma_dependencias FOR DELETE TO authenticated USING (public.fn_elev_is_admin());

CREATE INDEX elev_cronograma_etapas_projeto_ordem_idx ON public.elev_cronograma_etapas (projeto_id, ordem, id);
CREATE INDEX elev_cronograma_etapa_unidades_etapa_idx ON public.elev_cronograma_etapa_unidades (etapa_id, unidade_id);
CREATE INDEX elev_cronograma_faciais_participacao_idx ON public.elev_cronograma_faciais (etapa_unidade_id, ordem, id);
CREATE INDEX elev_cronograma_dependencias_etapa_idx ON public.elev_cronograma_dependencias (etapa_id);

CREATE OR REPLACE FUNCTION public.fn_elev_cronograma_validar_datas()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.data_inicio IS NOT NULL AND NEW.data_fim IS NOT NULL AND NEW.data_fim < NEW.data_inicio THEN
    RAISE EXCEPTION 'data_fim_anterior_data_inicio';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_elev_cronograma_touch()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.atualizado_em := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_elev_cronograma_validar_dependencia()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_projeto bigint;
  v_dep_projeto bigint;
BEGIN
  IF NEW.etapa_id = NEW.depende_de_etapa_id THEN
    RAISE EXCEPTION 'etapa_nao_pode_depender_de_si';
  END IF;
  SELECT projeto_id INTO v_projeto FROM public.elev_cronograma_etapas WHERE id = NEW.etapa_id;
  SELECT projeto_id INTO v_dep_projeto FROM public.elev_cronograma_etapas WHERE id = NEW.depende_de_etapa_id;
  IF v_projeto IS DISTINCT FROM v_dep_projeto THEN
    RAISE EXCEPTION 'dependencia_deve_pertencer_ao_mesmo_projeto';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER elev_cronograma_projetos_validar_datas BEFORE INSERT OR UPDATE ON public.elev_cronograma_projetos FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_validar_datas();
CREATE TRIGGER elev_cronograma_etapas_validar_datas BEFORE INSERT OR UPDATE ON public.elev_cronograma_etapas FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_validar_datas();
CREATE TRIGGER elev_cronograma_unidades_validar_datas BEFORE INSERT OR UPDATE ON public.elev_cronograma_etapa_unidades FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_validar_datas();
CREATE TRIGGER elev_cronograma_projetos_touch BEFORE UPDATE ON public.elev_cronograma_projetos FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_touch();
CREATE TRIGGER elev_cronograma_etapas_touch BEFORE UPDATE ON public.elev_cronograma_etapas FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_touch();
CREATE TRIGGER elev_cronograma_unidades_touch BEFORE UPDATE ON public.elev_cronograma_etapa_unidades FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_touch();
CREATE TRIGGER elev_cronograma_faciais_touch BEFORE UPDATE ON public.elev_cronograma_faciais FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_touch();
CREATE TRIGGER elev_cronograma_dependencias_validar BEFORE INSERT OR UPDATE ON public.elev_cronograma_dependencias FOR EACH ROW EXECUTE FUNCTION public.fn_elev_cronograma_validar_dependencia();

ALTER PUBLICATION supabase_realtime ADD TABLE public.elev_cronograma_projetos;
ALTER PUBLICATION supabase_realtime ADD TABLE public.elev_cronograma_etapas;
ALTER PUBLICATION supabase_realtime ADD TABLE public.elev_cronograma_etapa_unidades;
ALTER PUBLICATION supabase_realtime ADD TABLE public.elev_cronograma_faciais;
ALTER PUBLICATION supabase_realtime ADD TABLE public.elev_cronograma_dependencias;